# To use this image with docker-compose please look at the examples in example/docker-compose.
# This file is used for development together with .env which you can create by copying .env.default.
version: '3'
services:
  mediawiki_wiki:
    build: .
    container_name: mediawiki_wiki
    environment:
      MEDIAWIKI_SERVER: ${DOCU_SERVER_URL}
      MEDIAWIKI_SITENAME: ${DOCU_SITENAME}
      MEDIAWIKI_LANGUAGE_CODE: ${DOCU_LANGUAGE_CODE}
      MEDIAWIKI_SECRET_KEY: ${SECRET_KEY}
      #MEDIAWIKI_META_NAMESPACE: MyNamespace
      MEDIAWIKI_DB_TYPE: mysql
      MEDIAWIKI_DB_HOST: ${DB_HOST}
      MEDIAWIKI_DB_PORT: 3306
      MEDIAWIKI_DB_NAME: ${DB_NAME}
      MEDIAWIKI_DB_USER: ${DB_USER}
      MEDIAWIKI_DB_PREFIX: mywiki_
      MEDIAWIKI_DB_TABLE_OPTIONS: ENGINE=InnoDB, DEFAULT CHARSET=binary
      MEDIAWIKI_DB_PASSWORD: ${DB_PASSWORD}
      MEDIAWIKI_ENABLE_UPLOADS: 1
      MEDIAWIKI_MAX_UPLOAD_SIZE: ${UPLOAD_SIZE}
      MEDIAWIKI_DEFAULT_SKIN: ${SKIN}
      MEDIAWIKI_SMTP: 1
      MEDIAWIKI_SMTP_SSL_VERIFY_PEER: 0
      MEDIAWIKI_SMTP_HOST: ${SMTP_HOST}
      MEDIAWIKI_SMTP_IDHOST: ${SMTP_IDHOST}
      MEDIAWIKI_SMTP_PORT: 587
      MEDIAWIKI_SMTP_AUTH: 1
      MEDIAWIKI_SMTP_USERNAME: ${SMTP_USERNAME}
      MEDIAWIKI_SMTP_PASSWORD: ${SMTP_PASSWORD}
      MEDIAWIKI_EMERGENCY_CONTACT: ${EMERGENCY_CONTACT}
      MEDIAWIKI_PASSWORD_SENDER: ${PASSWORD_SENDER}
      MEDIAWIKI_EXTENSION_VISUAL_EDITOR_ENABLED: 1
      MEDIAWIKI_EXTENSION_USER_MERGE_ENABLED: 1
      MEDIAWIKI_FILE_EXTENSIONS: png,gif,jpg,jpeg,webp,pdf
      MEDIAWIKI_DEBUG: 1
      PHPFPM_WORKERS_START: 1
      PHPFPM_WORKERS_MIN: 1
      PHPFPM_WORKERS_MAX: 20
      PARSOID_WORKERS: 1
    ports:
    - 127.0.0.1:8080:8080
    volumes:
    - ./data/images:/images
    - ./data/logo.png:/var/www/mediawiki/resources/assets/wiki.png:ro
    - ./data/ExtraLocalSettings.php:/var/www/mediawiki/ExtraLocalSettings.php:ro